### ISSUE TITLE
Copy app creates double apps and timeout errors

### ISSUE THREAD

**Issue by QHose** [stefanwalther/qrs#10]
hi Stefan,

 If I use the code of NPM QRS, I get double apps, and timeout messages. If I just create my own HTTP call it works perfectly. Can you see the issue?
1. I don' see double log entries in node, but I do have double apps in Sense...

//CODE WITH NPM QRS, THAT GENERATES DOUBLE APPS

```
function copyApp (guid, name) {
    console.log('Copy template: '+guid+' to new app: '+name);
    check(guid, String);
    check(name, String);
    return qrs.post('/qrs/app/'+guid+'/copy', [{"key": "name", "value": name}])
    .then(
        function fulfilled (result) {
            console.log('result of copy app promise', result);
            return result;
        },
        function Rejected (error){
            console.error('Promise Rejected: Error when trying to copy the app', error);
            throw new Meteor.Error('App copy failed', 'App copy failed');
        })
};

```

//MY OWN CODE THAT WORKS FINE

```
function copyApp (guid, name) {
    console.log('Copy template: '+guid+' to new app: '+name);
    check(guid, String);
    check(name, String);

    return new Promise(function(resolve, reject){ 
        HTTP.call( 'post', 'http://'+config.host+'/'+config.virtualProxy+'/qrs/app/'+guid+'/copy?name='+name+'&xrfkey='+config.xrfkey, 
        {
            headers: {
                'hdr-usr' : config.headerValue,
                'X-Qlik-xrfkey': config.xrfkey
            }
        }, function( error, response ) {
            if ( error ) {
                console.error( error );
                throw new Meteor.Error('error app copy', error)
                reject(error);
            } else {
                console.log( response );
                resolve('copy app success');
            }
        });
    })

};
```

**Comment by QHose** [comment]
Also this function creates timeouts and errors

![image](https://cloud.githubusercontent.com/assets/12411165/15601737/5cdc02a4-23f1-11e6-8285-05fd6679f1a8.png)

```
function getStreams () {
    return qrs.get('/qrs/stream/full');
};

```

**Comment by QHose** [comment]
mmm, the QMC has also issues to delete the app... so maybe not only QRS NPM issue. (my laptop connects to the vm running sense, and my  node tool also runs on the laptop)

![image](https://cloud.githubusercontent.com/assets/12411165/15601805/da762244-23f1-11e6-8da6-e3a050563d9e.png)

now the streams have been removed, but the I get still errors from npm qrs, when I want to get my streams

![image](https://cloud.githubusercontent.com/assets/12411165/15601896/5fe0b64c-23f2-11e6-9080-9aabfcdb9ec2.png)

**Comment by QHose** [comment]
So, this is caused by the fact that i don't throttle my requests to sense qrs
1. Could you implement this limiter in your code?

**Comment by QHose** [comment]
Btw, i noticed you can seriously make sense qmc itself unresponsive by this... Even after my calls finished

**Comment by stefanwalther** [comment]
I think there is some general timeout handling necessary in this, will investigate as soon as I have time ;-)
