### ISSUE TITLE
No longer works after upgrade to QS 3.0.1

### ISSUE THREAD

**Issue by mountaindude** [stefanwalther/qrs#11]
Been using the qrs package to start tasks (using /qrs/task endpoint) under QS 2.2.4, has worked fine. After upgrade to QS 3.0.1 the above no longer works. 
Looking into reasons/options now, still wanted to report it.

/Göran

**Comment by stefanwalther** [comment]
Hi, thx for reporting. Can you add more details (logs, code-samples, etc.)?
