### ISSUE TITLE
Request Timeout limit too low

### ISSUE THREAD

**Issue by qlikbez** [stefanwalther/qrs#13]
The current request timeout is 2000ms and it is not enought for some Sense SDK requests as "UploadApp" and "ExportCertificates".

These requests return an error "ETIMEDOUT", even if the requests are correctly completed.

Using the ["post" method](https://github.com/stefanwalther/qrs#post) we can't force the timeout option. I can force this timeout only with ["request" method](https://github.com/stefanwalther/qrs#request) in this way:
`qrs.request( "post", "/qrs/certificatedistribution/exportcertificates", null, {"machineNames": machineNames,"certificatePassword": password,"includeSecretsKey": incudeSecretKey,"ExportFormat": "Windows"}, null, {timeout: 5000} );`

It could be nice if the timeout is set to 5 seconds for example.

**Comment by stefanwalther** [comment]
Yep, this should really be configurable. Will add that.
Do you want to make a PR?
