### ISSUE TITLE
Documentation for 3.1.1 - Header Value for User Directory

### ISSUE THREAD

**Issue by johannva** [stefanwalther/qrs#15]
Using the delivered documentation for certificate auth on Qlik Sense Server 3.1.1, I get an error 'Unknown users not allowed for repository calls, missing or malformed http header: X-Qlik-User'.  By replacing colons with the equals symbol in the following line in the config, I was able to make a successful call to the repository:

`headerValue: 'UserDirectory:Internal;UserId:sa_repository' `

changed to 

`headerValue: 'UserDirectory=Internal;UserId=sa_repository' `

**Comment by domski74** [comment]
Thanks for this; couldn't figure why it kept failing and this fixed it.

**Comment by github-aman** [comment]
@johannva 
Can you please update me the exact config file name?
Thanks..
