### ISSUE TITLE
Header authentication not working with proxy server

### ISSUE THREAD

**Issue by Mian007** [stefanwalther/qrs#20]
`var config = {
  authentication: 'header',
  host: '162.209.126.33',
  useSSL: true,
  virtualProxy: 'hdr',
  headerKey: 'hdr-usr',
  headerValue: 'ALOPOLIS-01\\demo'
}; 

var qrs = new QRS( config );

// Now run your command like
qrs.get('/hdr/qrs/about')
.then(function(data) {
    console.log('about:',data);

}, function(err) {
    console.error(err);
});`

when i run this code it give error on console : 
{ error:
   { Error: unable to verify the first certificate
       at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
       at emitNone (events.js:86:13)
       at TLSSocket.emit (events.js:188:7)
       at TLSSocket._finishInit (_tls_wrap.js:610:8)
       at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' },
  response: undefined }
undefined

**Comment by Mian007** [comment]
i also tried by postman it shows this error
![screenshot_8](https://user-images.githubusercontent.com/26344379/30793328-985ddfce-a1da-11e7-980d-1c979c2c76db.png)

**Comment by QHose** [comment]
Hi,

You have a wrong format for your xref parameter in the url
Search for " header authentication" in 
http://integration.qlik.com/slideGenerator

![image](https://user-images.githubusercontent.com/12411165/30806510-5f665450-a1f6-11e7-8d80-1d7ea8f193e1.png)
