### ISSUE TITLE
Certificate auth (INVALID_PURPOSE)

### ISSUE THREAD

**Issue by tlinteau** [stefanwalther/qrs#21]
Using a very basic example to see if node.js will work for my needs (previously wrote all this stuff in C#). Here is my code:

```
var QRS = require('qrs');

var config = {
    "authentication": 'certificates',
    "host": 'localhost',
    "useSSL": true,
    "cert": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\client.pem',
    "key": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\client_key.pem',
    "ca": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\root.pem',
    "port": 4242,
    "headerKey": 'X-Qlik-User',
    "headerValue": 'UserDirectory:Internal;UserId:sa_repository',
};

var qrs = new QRS( config );
 
qrs.get( 'qrs/about')
       .then( function ( data) {
            console.log('about: ', data );
        }, function ( err ) {
            console.error( err );
        });
```

I've also tried using a certificate in PEM format that I've exported from the QMC. I get the same results:

`{ error: { Error: unsupported certificate purpose
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'INVALID_PURPOSE' },
  response: undefined }`

Not sure if it's something I'm doing wrong or there's a legit issue with the module. Any guidance is appreciated. The version of sense I'm working on right now is Nov 2017

**Comment by QHose** [comment]
Hi

Are you Sure the User Running node has windows admin privileges?

Try to put the certs in another folder

Verstuurd vanaf mijn iPhone

Op 15 mei 2018 om 21:24 heeft tlinteau <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Using a very basic example to see if node.js will work for my needs (previously wrote all this stuff in C#). Here is my code:

var QRS = require('qrs');

var config = {
    "authentication": 'certificates',
    "host": 'localhost',
    "useSSL": true,
    "cert": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\client.pem',
    "key": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\client_key.pem',
    "ca": 'C:\\ProgramData\\Qlik\\Sense\\Repository\\Exported Certificates\\.Local Certificates\\root.pem',
    "port": 4242,
    "headerKey": 'X-Qlik-User',
    "headerValue": 'UserDirectory:Internal;UserId:sa_repository',
};

var qrs = new QRS( config );

qrs.get( 'qrs/about')
       .then( function ( data) {
            console.log('about: ', data );
        }, function ( err ) {
            console.error( err );
        });


I've also tried using a certificate in PEM format that I've exported from the QMC. I get the same results:

{ error: { Error: unsupported certificate purpose at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34) at TLSSocket.emit (events.js:182:13) at TLSSocket._finishInit (_tls_wrap.js:635:8) code: 'INVALID_PURPOSE' }, response: undefined }

Not sure if it's something I'm doing wrong or there's a legit issue with the module. Any guidance is appreciated.

**Comment by tlinteau** [comment]
Moved my code over so its using a fresh installation of sense (April 2018). Exported a cert and moved it into another directory. Logged in as administrator and running an elevated command prompt. Same result.

![image](https://user-images.githubusercontent.com/6095644/40149973-ee095abc-5944-11e8-883e-4844fbb35387.png)
7

**Comment by QHose** [comment]
Mmmm, I support this really is a lower level node and QRS module issue…

https://stackoverflow.com/questions/11884731/openssl-invalid-purpose?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by tlinteau** [comment]
I think the issue is due to the fact that the QS exported cert is self-signed. Adding **process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";** to the code seems to have done the trick.

```
var QRS = require('qrs'); 

var config = { 
"authentication": 'certificates', 
"host": 'localhost', 
"useSSL": true, 
"cert": 'C:\\Users\\Administrator\\Documents\\Node Projects\\Cert Store\\client.pem', 
"key": 'C:\\Users\\Administrator\\Documents\\Node Projects\\Cert Store\\client_key.pem', 
"ca": 'C:\\Users\\Administrator\\Documents\\Node Projects\\Cert Store\\root.pem', 
"port": 4242, 
"headerKey": 'X-Qlik-User', 
"headerValue": 'UserDirectory=Internal;UserId=sa_repository', 
}; 
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
var qrs = new QRS( config ); 

qrs.get( '/qrs/about') 
.then( function ( data) { 
console.log('about: ', data ); 
}, function ( err ) { 
console.error( err ); 
}); 
```

Results:

```
C:\Users\Administrator\Documents\Node Projects>node app.js
about:  { buildVersion: '20.4.2.0',
  buildDate: '9/20/2013 10:09:00 AM',
  databaseProvider: 'Devart.Data.PostgreSql',
  nodeType: 1,
  sharedPersistence: true,
  requiresBootstrap: false,
  singleNodeOnly: false,
  schemaPath: 'About' }

C:\Users\Administrator\Documents\Node Projects>
```
