### ISSUE TITLE
[Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

### ISSUE THREAD

**Issue by goldbergjeffrey** [stefanwalther/qrs#4]
Attempting header configuration with certificates I'm running into the following error:

[Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

Code Sample:
`var QRS = require('qrs');`
`var fs = require('fs');`
`var config = require('./config');`

`var qrsconfig = {
    authentication: 'header',
    //authentication: 'certificates',
    host:'sense22.112adams.local',
    useSSL: true,
    //port: 4242,
    virtualProxy: 'sdkheader',
    headerKey: 'hdr-sense-sdkheader',
    headerValue: 'administrator',
    //headerKey: 'X-Qlik-User',
    //headerValue: 'UserDirectory:Internal;UserId:sa_repository',
    xrfkey: 'ABCDEFG123456789' ,
    cert: fs.readFileSync(config.certificates.client),
    key: fs.readFileSync(config.certificates.client_key),
    ca: fs.readFileSync(config.certificates.root)
};`

`var qrs = new QRS(qrsconfig);`

`qrs.get('qrs/app')
.then(function(data)
{
    console.log(data);
}
, function(err)
{
    console.log(err);
});`

Thoughts?

**Comment by stefanwalther** [comment]
Why closed, what was the problem? How did you solve it? 
Anything I can improve?
