### ISSUE TITLE
[Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

### ISSUE THREAD

**Issue by goldbergjeffrey** [stefanwalther/qrs#5]
Attempting header configuration with certificates I'm running into the following error:

[Error: unable to verify the first certificate] code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'

Code Sample:
`var QRS = require('qrs');`
`var fs = require('fs');`
`var config = require('./config');`

`var qrsconfig = {
    authentication: 'header',
    host:'sense22.112adams.local',
    useSSL: true,
    virtualProxy: 'sdkheader',
    headerKey: 'hdr-sense-sdkheader',
    headerValue: 'administrator',
    xrfkey: 'ABCDEFG123456789' ,
    cert: fs.readFileSync(config.certificates.client),
    key: fs.readFileSync(config.certificates.client_key),
    ca: fs.readFileSync(config.certificates.root)
};`

`var qrs = new QRS(qrsconfig);`

`qrs.get('qrs/app')
.then(function(data)
{
    console.log(data);
}
, function(err)
{
    console.log(err);
});`

Thoughts?

**Comment by stefanwalther** [comment]
How does your config look like?

**Comment by goldbergjeffrey** [comment]
closed the other because it was a dupe.  Sorry about that.  Couldn't figure out how to delete.

Here is my config.js

`var path = require('path');
var extend = require('extend');

//For production
//var certPath = 'C:/ProgramData/Qlik/Sense/Repository/Exported Certificates/.Local Certificates';

var certPath = 'C:/masterlib/certs';
var routePath = path.join(__dirname, 'server/routes/');
var publicPath = path.join(__dirname, 'public/');

var config = extend(true, {
    port: 8590,
    enginePort: 4747,
    hostname: 'sense22.112adams.local',
    //virtualProxy: 'sdkheader',
    //headerName: 'hdr-sense-sdkheader',
    userDirectory: 'sense22',
    userId: 'administrator',
    certificates: {
        client: path.resolve(certPath, 'client.pem'),
        client_key: path.resolve(certPath,'client_key.pem'),
        server: path.resolve(certPath, 'server.pem'),
        server_key: path.resolve(certPath, 'server_key.pem'),
        root: path.resolve(certPath,'root.pem')
    },
    routePath: routePath,
    publicPath: publicPath,
    appName: 'Metrics Libary'
});

module.exports = config;`

**Comment by stefanwalther** [comment]
Hi, please try to add `"rejectUnauthorized": false,` to the config, does it work then?

**Comment by goldbergjeffrey** [comment]
I did, but it did not change the behavior.  I will test again and let you know.

**Comment by stefanwalther** [comment]
bump

**Comment by goldbergjeffrey** [comment]
Closing issue.  My issue is that I used a root property instead of a ca property for the root cert.
